### ISSUE TITLE
Warning when executing script: Notify was imported without specifying a version first.

### ISSUE THREAD

**Issue by xuiqzy** [gkarakou/systemd-denotify#3]
When you execute the script there is the following warning:

> /usr/lib/python2.7/site-packages/denotify/servicestatuschecker.py:7: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
>   from gi.repository import Notify

Maybe you could add a minimum version that is needed to fix it :)

**Comment by gkarakou** [comment]
Ok, thanks for noticing it.

**Comment by gkarakou** [comment]
Should by now be fixed with the latest commit.
