### ISSUE TITLE
Implement versioning using git tagging

### ISSUE THREAD

**Issue by ilstam** [gkarakou/systemd-denotify#4]
Please consider using git tagging in order to have discrete versions (I suggest annotated tags): https://git-scm.com/book/en/v2/Git-Basics-Tagging

This will help in packaging. For example, atm, users get confused and constantly flag the package as out-of-date in AUR.

Thanks.

**Comment by gkarakou** [comment]
Should be now fixed with a tag v1.2

**Comment by ilstam** [comment]
Please push the tag to this remote repository. You can do this by running: git push --tags
